version: '3.8'
services:
  spark-master:
    image: apache/spark-py:latest
    user: root
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_NO_DAEMONIZE=1
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - .:/app  # 🔥 Add this

  spark-worker-1:
    image: apache/spark-py:latest
    user: root
    depends_on:
      - spark-master
    command:
      - "/opt/spark/sbin/start-worker.sh"
      - "spark://spark-master:7077"
    environment:
      - SPARK_NO_DAEMONIZE=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
    ports:
      - "8081:8081"
    volumes:
      - .:/app  # 🔥 Add this too
      - spark-work:/tmp/spark/work

  spark-worker-2:
    image: apache/spark-py:latest
    user: root
    depends_on:
      - spark-master
    command:
      - "/opt/spark/sbin/start-worker.sh"
      - "spark://spark-master:7077"
    environment:
      - SPARK_NO_DAEMONIZE=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
    ports:
      - "8082:8081"
    volumes:
      - .:/app  # 🔥 Add this too
      - spark-work:/tmp/spark/work

  jupyter:
    build: .
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077

volumes:
  spark-work:
